auth_enabled: false

server:
  http_listen_port: 3100
  log_level: warn

common:
  instance_addr: 127.0.0.1
  replication_factor: 1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

#ruler:
#  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false

frontend:
  max_outstanding_per_tenant: 2048

limits_config:
  max_query_series: 100000
  max_entries_limit_per_query: 100000
  query_timeout: 3m
  split_queries_by_interval: 0

#chunk_store_config:
#  chunk_cache_config:
#    enable_fifocache: false
