# Prometheus Config

global:
  scrape_interval:     5m # Default 1min
  evaluation_interval: 5m # Default 1min
  scrape_timeout:      5s # Default 10s

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets: ['localhost:9093']

# Load rules and evaluate them according to evaluation_interval
rule_files:

# Scrape configuration
scrape_configs:
  - job_name: unbound
    scrape_interval: 30s
    scrape_timeout: 5s
    static_configs:
      - targets: ['unbound-exporter:9167']
